### ISSUE TITLE
Add custom Vote categories and incident kinds

### ISSUE THREAD

**Issue by SSchulze1989** [SSchulze1989/iRLeagueManager#70]
.

**Comment by SSchulze1989** [comment]
Decided against doing a quick fix for the missing Racing incident category. Instead i will aim to have the proper implementation of custom categories and incident Kinds ready next up.

**Comment by SSchulze1989** [comment]
# Tasks
- [ ] Add Custom Incident Kind / Vote Categories to Database
- [ ] Add DTO classes
- [ ] Implement Database mapping
- [ ] Add Model classes
- [ ] Populate list with initial values
- [ ] Changes to ReviewViewModel
- [ ] Changes to ReviewsControl and ReviewEditControl
